"""empty message

Revision ID: 85e8619530a6
Revises: ce19315e2ed5
Create Date: 2022-03-03 00:39:35.977157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e8619530a6'
down_revision = 'ce19315e2ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'start_hour',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('classes', 'end_hour',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'end_hour',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('classes', 'start_hour',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
