"""empty message

Revision ID: adc2bda725b1
Revises: b674af95db62
Create Date: 2022-03-03 00:22:07.797830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc2bda725b1'
down_revision = 'b674af95db62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'saturday')
    op.drop_column('classes', 'sunday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('sunday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('saturday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
