"""empty message

Revision ID: ce19315e2ed5
Revises: adc2bda725b1
Create Date: 2022-03-03 00:32:24.406846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce19315e2ed5'
down_revision = 'adc2bda725b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'start_hour',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('classes', 'end_hour',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'end_hour',
               existing_type=sa.VARCHAR(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('classes', 'start_hour',
               existing_type=sa.VARCHAR(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
